# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SmartDog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from Label import Label

class Ui_Smartdog(object):
    def setupUi(self, Smartdog):
        Smartdog.setObjectName("Smartdog")
        Smartdog.resize(1500, 1000)
        Smartdog.setMinimumSize(QtCore.QSize(1500, 1000))
        Smartdog.setMaximumSize(QtCore.QSize(1500, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/dog1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Smartdog.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Smartdog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_SiamrpnA1 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox_SiamrpnA1.setFont(font)
        self.checkBox_SiamrpnA1.setObjectName("checkBox_SiamrpnA1")
        self.gridLayout_6.addWidget(self.checkBox_SiamrpnA1, 1, 0, 1, 1)
        self.checkBox_SiamrpnA2 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox_SiamrpnA2.setFont(font)
        self.checkBox_SiamrpnA2.setObjectName("checkBox_SiamrpnA2")
        self.gridLayout_6.addWidget(self.checkBox_SiamrpnA2, 2, 0, 1, 1)
        self.checkBox_SiamrpnM = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox_SiamrpnM.setFont(font)
        self.checkBox_SiamrpnM.setObjectName("checkBox_SiamrpnM")
        self.gridLayout_6.addWidget(self.checkBox_SiamrpnM, 3, 0, 1, 1)
        self.checkBox_SiamrpnR1 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox_SiamrpnR1.setFont(font)
        self.checkBox_SiamrpnR1.setObjectName("checkBox_SiamrpnR1")
        self.gridLayout_6.addWidget(self.checkBox_SiamrpnR1, 4, 0, 1, 1)
        self.checkBox_Siammask = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox_Siammask.setFont(font)
        self.checkBox_Siammask.setObjectName("checkBox_Siammask")
        self.gridLayout_6.addWidget(self.checkBox_Siammask, 0, 0, 1, 1)
        self.checkBox_SiamrpnR2 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox_SiamrpnR2.setFont(font)
        self.checkBox_SiamrpnR2.setObjectName("checkBox_SiamrpnR2")
        self.gridLayout_6.addWidget(self.checkBox_SiamrpnR2, 5, 0, 1, 1)
        self.checkBox_SiamrpnR3 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.checkBox_SiamrpnR3.setFont(font)
        self.checkBox_SiamrpnR3.setObjectName("checkBox_SiamrpnR3")
        self.gridLayout_6.addWidget(self.checkBox_SiamrpnR3, 6, 0, 1, 1)
        self.btn_algo_ok = QtWidgets.QPushButton(self.groupBox)
        self.btn_algo_ok.setMinimumSize(QtCore.QSize(100, 60))
        self.btn_algo_ok.setObjectName("btn_algo_ok")
        self.gridLayout_6.addWidget(self.btn_algo_ok, 7, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 2, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_show = Label(self.widget)
        self.label_show.setMinimumSize(QtCore.QSize(1000, 600))
        self.label_show.setMaximumSize(QtCore.QSize(1000, 600))
        self.label_show.setSizeIncrement(QtCore.QSize(900, 800))
        self.label_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_show.setText("")
        self.label_show.setObjectName("label_show")
        self.gridLayout_2.addWidget(self.label_show, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(900, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.btn_open_camera = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_open_camera.setMinimumSize(QtCore.QSize(220, 80))
        self.btn_open_camera.setMaximumSize(QtCore.QSize(220, 80))
        self.btn_open_camera.setObjectName("btn_open_camera")
        self.gridLayout.addWidget(self.btn_open_camera, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(163, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.btn_open_video = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_open_video.setMinimumSize(QtCore.QSize(220, 80))
        self.btn_open_video.setMaximumSize(QtCore.QSize(220, 80))
        self.btn_open_video.setObjectName("btn_open_video")
        self.gridLayout.addWidget(self.btn_open_video, 0, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(164, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 1)
        self.btn_open_camera.raise_()
        self.btn_open_video.raise_()
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_select_target = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_select_target.setMinimumSize(QtCore.QSize(140, 60))
        self.btn_select_target.setMaximumSize(QtCore.QSize(140, 60))
        self.btn_select_target.setObjectName("btn_select_target")
        self.gridLayout_5.addWidget(self.btn_select_target, 0, 0, 1, 1)
        self.btn_track_start = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_track_start.setMinimumSize(QtCore.QSize(140, 60))
        self.btn_track_start.setMaximumSize(QtCore.QSize(140, 60))
        self.btn_track_start.setObjectName("btn_track_start")
        self.gridLayout_5.addWidget(self.btn_track_start, 1, 0, 1, 1)
        self.btn_track_over = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_track_over.setMinimumSize(QtCore.QSize(140, 60))
        self.btn_track_over.setMaximumSize(QtCore.QSize(140, 60))
        self.btn_track_over.setObjectName("btn_track_over")
        self.gridLayout_5.addWidget(self.btn_track_over, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textBws_show_process = QtWidgets.QTextBrowser(self.groupBox_3)
        self.textBws_show_process.setObjectName("textBws_show_process")
        self.gridLayout_3.addWidget(self.textBws_show_process, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 1, 1, 2)
        self.gridLayout_4.setColumnStretch(0, 2)
        self.gridLayout_4.setColumnStretch(1, 8)
        self.gridLayout_4.setColumnStretch(2, 1)
        Smartdog.setCentralWidget(self.centralwidget)

        self.retranslateUi(Smartdog)
        QtCore.QMetaObject.connectSlotsByName(Smartdog)

    def retranslateUi(self, Smartdog):
        _translate = QtCore.QCoreApplication.translate
        Smartdog.setWindowTitle(_translate("Smartdog", "SmartDog"))
        self.groupBox.setTitle(_translate("Smartdog", "算法选择"))
        self.checkBox_SiamrpnA1.setText(_translate("Smartdog", "SiamRPN-AlexNet-1"))
        self.checkBox_SiamrpnA2.setText(_translate("Smartdog", "SiamRPN-AlexNet-2"))
        self.checkBox_SiamrpnM.setText(_translate("Smartdog", "SiamRPN-Mobilev2"))
        self.checkBox_SiamrpnR1.setText(_translate("Smartdog", "SiamRPN-Resnet50-1"))
        self.checkBox_Siammask.setText(_translate("Smartdog", "SiamMask-Resnet50"))
        self.checkBox_SiamrpnR2.setText(_translate("Smartdog", "SiamRPN-Resnet50-2"))
        self.checkBox_SiamrpnR3.setText(_translate("Smartdog", "SiamRPN-Resnet50-3"))
        self.btn_algo_ok.setText(_translate("Smartdog", "确认"))
        self.groupBox_2.setTitle(_translate("Smartdog", "跟踪方式"))
        self.btn_open_camera.setText(_translate("Smartdog", "摄像头跟踪"))
        self.btn_open_video.setText(_translate("Smartdog", "视频文件跟踪"))
        self.groupBox_4.setTitle(_translate("Smartdog", "跟踪选择"))
        self.btn_select_target.setText(_translate("Smartdog", "选择跟踪目标"))
        self.btn_track_start.setText(_translate("Smartdog", "开始跟踪"))
        self.btn_track_over.setText(_translate("Smartdog", "结束跟踪"))
        self.groupBox_3.setTitle(_translate("Smartdog", "进程显示"))
import SmartDog_rc
